#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

define('ROOT_DIR', __DIR__ . DIRECTORY_SEPARATOR);

set_time_limit(0);


use CodeSchoolBundle\Command\CodeSchoolParserCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CodeSchoolParserCommand());
$application->run();
